package vistas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.beans.Mesero;
import modelo.dao.MeseroDAO;

public class MeserosView extends javax.swing.JFrame {

    private List<Mesero> meseros;

    public MeserosView() {
        setLookAndFeel();
        initComponents();
        meseros = MeseroDAO.getMeseros();
        cargarMeserosEnTabla();
    }
    
    private void cargarMeserosEnTabla(){
        String [] columnas = {"CLAVE","NOMBRE","APELLIDOS"};
        DefaultTableModel model = new DefaultTableModel();
        model = new DefaultTableModel(new Object[0][0], columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        if(meseros!=null){
            for(Mesero m : meseros){
                Object fila[] = new Object[4];
                fila[0] = m.getIdMesero();
                fila[1] = m.getNombre();
                fila[2] = m.getApellidos();
                model.addRow(fila);
            }
        }
        this.tbl_datos.setModel(model);
    }
    
    private void setLookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeserosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeserosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeserosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeserosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_filtro_nombre = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar Meseros");
        setMinimumSize(new java.awt.Dimension(850, 500));

        jLabel1.setText("Buscar por nombre:");
        jPanel1.add(jLabel1);

        txt_filtro_nombre.setPreferredSize(new java.awt.Dimension(120, 22));
        jPanel1.add(txt_filtro_nombre);

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/search.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar);

        jLabel2.setPreferredSize(new java.awt.Dimension(50, 0));
        jPanel1.add(jLabel2);

        btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/add.png"))); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.setToolTipText("");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar);

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/edit.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_datos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String nombre = this.txt_filtro_nombre.getText();
        if(nombre==null || nombre.trim().isEmpty()){
            this.meseros = MeseroDAO.getMeseros();
        }else{
            this.meseros = MeseroDAO.buscarPorNombre(nombre.trim());
        }
        cargarMeserosEnTabla();
        if(this.meseros.size() == 0){
            JOptionPane.showMessageDialog(this, "No se encontraron registros",
                                                "Información", 
                                                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        MeserosDialog dialogo = new MeserosDialog(this, true, null);
        this.meseros = MeseroDAO.getMeseros();
        cargarMeserosEnTabla();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int indexselected = this.tbl_datos.getSelectedRow();
        if(indexselected < 0){
            JOptionPane.showMessageDialog(this, 
                        "Debes seleccionar el registro que deseas eliminar",
                        "Advertencia", 
                        JOptionPane.WARNING_MESSAGE);
            return;
        }
        Mesero mesero = this.meseros.get(indexselected); 
        MeserosDialog dialogo = new MeserosDialog(this, true, mesero);
        this.meseros = MeseroDAO.getMeseros();
        cargarMeserosEnTabla();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int indexselected = this.tbl_datos.getSelectedRow();
        if(indexselected < 0){
            JOptionPane.showMessageDialog(this, 
                        "Debes seleccionar el registro que deseas eliminar",
                        "Advertencia", 
                        JOptionPane.WARNING_MESSAGE);
            return;
        }
        Integer idmesero = this.meseros.get(indexselected).getIdMesero();
        int respuesta = JOptionPane.showConfirmDialog(this,
                            "¿Borrar mesero seleccionado?",
                            "Borrar mesero",
                            JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            if(MeseroDAO.eliminar(idmesero)){
                JOptionPane.showMessageDialog(this, 
                        "Mesero eliminada correctamente",
                        "Confirmación", 
                        JOptionPane.INFORMATION_MESSAGE);
                this.meseros = MeseroDAO.getMeseros();
                cargarMeserosEnTabla();
            }else{
                JOptionPane.showMessageDialog(this, 
                        "No se puede eliminar el mesero seleccionad",
                        "Advertencia", 
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_datos;
    private javax.swing.JTextField txt_filtro_nombre;
    // End of variables declaration//GEN-END:variables
}
